# Generated by Django 4.2.29 on 2026-03-23 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('world_name', models.CharField(blank=True, help_text='The name of the setting or fictional world (e.g. Faerûn, Barovia)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('dungeon_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_dm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Player'), ('dm', 'Dungeon Master')], default='player', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campaign_manager.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('halfling', 'Halfling'), ('gnome', 'Gnome'), ('half_elf', 'Half-Elf'), ('half_orc', 'Half-Orc'), ('tiefling', 'Tiefling'), ('dragonborn', 'Dragonborn'), ('other', 'Other')], default='human', max_length=20)),
                ('character_class', models.CharField(choices=[('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard')], default='fighter', max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=10)),
                ('background_story', models.TextField(blank=True, help_text='Optional backstory for this character')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaign_manager.campaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('potion', 'Potion'), ('quest', 'Quest Item'), ('misc', 'Misc')], default='misc', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('value_gold', models.IntegerField(default=0, help_text='Value in gold pieces (gp)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Which session this is in the campaign (1, 2, 3, …)')),
                ('date', models.DateField()),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='How long the session ran, in hours (e.g., 3.5)', max_digits=4, null=True)),
                ('summary', models.TextField(blank=True, help_text='Recap notes for this session')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaign_manager.campaign')),
            ],
            options={
                'ordering': ['campaign', 'session_number'],
                'unique_together': {('campaign', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('deadly', 'Deadly')], default='medium', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('victory', 'Victory'), ('defeat', 'Defeat'), ('fled', 'Fled'), ('negotiated', 'Negotiated')], help_text='Leave blank if the encounter is still unresolved', max_length=20, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='campaign_manager.session')),
            ],
            options={
                'ordering': ['session', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaign_manager.campaignplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaign_manager.session')),
            ],
            options={
                'ordering': ['commenter'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='campaign_manager.campaign')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='campaign_manager.campaignplayer')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='campaign_manager.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_inventories', to='campaign_manager.item')),
            ],
            options={
                'unique_together': {('character', 'item')},
            },
        ),
    ]
